#!/bin/sh

fflag=no
cflag=no
mflag=no
iflag=no
jflag=1

optspec=":fcmij:-:"
while getopts "$optspec" optchar; do
    case "${optchar}" in
        # -)
        #     case "${OPTARG}" in
        #         loglevel)
        #             val="${!OPTIND}"; OPTIND=$(( $OPTIND + 1 ))
        #             echo "Parsing option: '--${OPTARG}', value: '${val}'" >&2;
        #             ;;
        #         loglevel=*)
        #             val=${OPTARG#*=}
        #             opt=${OPTARG%=$val}
        #             echo "Parsing option: '--${opt}', value: '${val}'" >&2
        #             ;;
        #         *)
        #             if [ "$OPTERR" = 1 ] && [ "${optspec:0:1}" != ":" ]; then
        #                 echo "Unknown option --${OPTARG}" >&2
        #             fi
        #             ;;
        #     esac;;
        f)
            fflag=yes
            ;;
        c)
            cflag=yes
            ;;
        m)
			mflag=yes
			;;
		i)
			iflag=yes
			;;
		j)
			jflag=$OPTARG
			;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
    esac
done

mkdir -p build
if [ $fflag = yes ] ; then rm -rf build ; mkdir build ; fi

if [ $cflag = yes ] ;
	then cd build .. ;
    CC=gcc-6 CXX=g++-6 \
	cmake -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/include/python3.5m/ \
          -DPYTHON_LIBRARY=usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/libpython3.5.dylib \
          -DPython_FRAMEWORKS=usr/local/Cellar/python3/3.5.1/Frameworks/ \
          -DCMAKE_INSTALL_PREFIX:PATH="$PWD/.." \
          -DUSE_TCMALLOC=ON -DUSE_OPENMP=ON -DUSE_LTO=ON ..;
	cd ..;
fi

if [ $mflag = yes ] ; then cd build .. ; make VERBOSE=0 -j${jflag}; cd ..; fi

if [ $iflag = yes ] ; then cd build .. ; make VERBOSE=0 -j${jflag} install; cd ..; fi

# ln -sf $PWD/lib/ov2sgd.dylib $PWD/lib/ov2sgd.so
# python setup.py build_ext --inplace
